version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Order-Service
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - laravel_net

  nginx:
    image: nginx:1.25.3
    container_name: laravel_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_net

  postgres:
    image: postgres:latest
    container_name: laravel_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_net

  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  pgdata:
